version: "3"
services:
  cron:
    # Build ./cron/Dockerfile into python_scripts
    build: ./python_scripts
    image: python_scripts
    depends_on:
      - router
      - middlemanager
      - historical
    environment:
      COORDINATOR_URL: coordinator:8081
      KAFKA_URL: kafka:29092
      SCHEMA_HOST: http://schema-registry
    # Run cron.sh
    command: ./cron.sh

  datasources:
    # Reuse: python_scripts
    image: python_scripts
    depends_on:
      - cron
    environment:
      COORDINATOR_URL: coordinator:8081
      KAFKA_URL: kafka:29092
      SCHEMA_HOST: http://schema-registry
    # Run datasources.sh
    command: ./datasources.sh

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          security:
            default-group: no-roles
            basic-auth:
              - username: ${AKHQ_USER}
                password: ${AKHQ_PASSWORD_HASH}
                groups:
                - admin
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
              schema-registry:
                url: "http://schema-registry:8084"
        micronaut:
          security:
            enabled: true
    ports:
      - 9000:8080
    links:
      - kafka
      - schema-registry
  zookeeper:
    image: "bitnami/zookeeper:3.8"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=dump
  kafka:
    image: "bitnami/kafka:3.3"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_SCHEMA_REGISTRY_URL=http://schema-registry:8084
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  # init-kafka:
  #   image: "bitnami/kafka:3.3"
  #   depends_on:
  #     - kafka
  #   entrypoint: [ '/bin/sh', '-c' ]
  #   command: |
  #     "
  #     # blocks until kafka is reachable
  #     kafka-topics --bootstrap-server kafka:9092 --list

  #     echo -e 'Creating kafka topics'
  #     kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic car --replication-factor 1 --partitions 1
  #     kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic bike --replication-factor 1 --partitions 1

  #     echo -e 'Successfully created the following topics:'
  #     kafka-topics --bootstrap-server kafka:9092 --list
  #     "
  schema-registry:
    image: "confluentinc/cp-schema-registry"
    ports:
      - 8084:8084
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:29092
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8084
      - SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=PLAINTEXT
    depends_on:
      - zookeeper
      - kafka
    restart: on-failure
  ## Druid services
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
  coordinator:
    build: ./docker
    container_name: coordinator
    volumes:
      - druid_shared:/opt/shared
      - coordinator_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - .env-druid
    environment:
      - druid_auth_authenticator_MyBasicMetadataAuthenticator_initialAdminPassword=${DRUID_PASSWORD}
  broker:
    build: ./docker
    container_name: broker
    volumes:
      - broker_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - .env-druid
    environment:
      - druid_auth_authenticator_MyBasicMetadataAuthenticator_initialAdminPassword=${DRUID_PASSWORD}

  historical:
    build: ./docker
    container_name: historical
    volumes:
      - druid_shared:/opt/shared
      - historical_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - .env-druid
    environment:
      - druid_auth_authenticator_MyBasicMetadataAuthenticator_initialAdminPassword=${DRUID_PASSWORD}

  middlemanager:
    build: ./docker
    container_name: middlemanager
    volumes:
      - druid_shared:/opt/shared
      - middle_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - .env-druid
    environment:
      - druid_auth_authenticator_MyBasicMetadataAuthenticator_initialAdminPassword=${DRUID_PASSWORD}

  router:
    build: ./docker
    container_name: router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - .env-druid
    environment:
      - druid_auth_authenticator_MyBasicMetadataAuthenticator_initialAdminPassword=${DRUID_PASSWORD}

  ## Superset services
  redis:
    image: redis:latest
    container_name: superset_cache
    volumes:
      - redis:/data

  db:
    env_file: .env-superset
    image: postgres:10
    container_name: superset_db
    volumes:
      - db_home:/var/lib/postgresql/data

  superset:
    env_file: .env-superset
    image: apache/superset:latest
    container_name: superset_app
    command: [ "/app/docker/docker-bootstrap.sh", "app-gunicorn" ]
    user: "root"
    ports:
      - 8088:8088
    depends_on:
      - db
      - redis
    volumes:
      - ./docker/superset:/app/docker
      - superset_home:/app/superset_home

  superset-init:
    image: apache/superset:latest
    container_name: superset_init
    command: [ "/app/docker/docker-init.sh" ]
    env_file: .env-superset
    depends_on:
      - db
      - redis
    user: "root"
    volumes:
      - ./docker/superset:/app/docker
      - superset_home:/app/superset_home
    environment:
      - ADMIN_PASSWORD=${SUPERSET_PASSWORD}

  superset-worker:
    image: apache/superset:latest
    container_name: superset_worker
    command: [ "/app/docker/docker-bootstrap.sh", "worker" ]
    env_file: .env-superset
    depends_on:
      - db
      - redis
    user: "root"
    volumes:
      - ./docker/superset:/app/docker
      - superset_home:/app/superset_home

  superset-worker-beat:
    image: apache/superset:latest
    container_name: superset_worker_beat
    command: [ "/app/docker/docker-bootstrap.sh", "beat" ]
    env_file: .env-superset
    depends_on:
      - db
      - redis
    user: "root"
    volumes:
      - ./docker/superset:/app/docker
      - superset_home:/app/superset_home

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
