# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x1a\x63om.codingharbour.protobuf\"y\n\nBikeRecord\x12\x13\n\x0bid_compteur\x18\x01 \x01(\t\x12\x14\n\x0cnom_compteur\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0b\n\x03lat\x18\x05 \x01(\x02\x12\x0b\n\x03lon\x18\x06 \x01(\x02\x12\x0c\n\x04\x64\x61te\x18\x07 \x01(\t\"\xdc\x01\n\tCarRecord\x12\x13\n\x0bid_compteur\x18\x01 \x01(\t\x12\x14\n\x0cnom_compteur\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x13\n\x0b\x65tat_trafic\x18\x04 \x01(\t\x12\x0b\n\x03lat\x18\x05 \x01(\x02\x12\x0b\n\x03lon\x18\x06 \x01(\x02\x12\x16\n\x0e\x63ompteur_amont\x18\x07 \x01(\t\x12\x1a\n\x12nom_compteur_amont\x18\x08 \x01(\t\x12\x18\n\x10id_compteur_aval\x18\t \x01(\t\x12\x19\n\x11nom_compteur_aval\x18\n \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BIKERECORD._serialized_start=44
  _BIKERECORD._serialized_end=165
  _CARRECORD._serialized_start=168
  _CARRECORD._serialized_end=388
# @@protoc_insertion_point(module_scope)
